package com.msr.nbmusic.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.msr.nbmusic.bean.db.LocalMusic;

import com.msr.nbmusic.greendao.LocalMusicDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localMusicDaoConfig;

    private final LocalMusicDao localMusicDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localMusicDaoConfig = daoConfigMap.get(LocalMusicDao.class).clone();
        localMusicDaoConfig.initIdentityScope(type);

        localMusicDao = new LocalMusicDao(localMusicDaoConfig, this);

        registerDao(LocalMusic.class, localMusicDao);
    }
    
    public void clear() {
        localMusicDaoConfig.clearIdentityScope();
    }

    public LocalMusicDao getLocalMusicDao() {
        return localMusicDao;
    }

}
